.\" THE BEER-WARE LICENSE (Revision 4711):
.\" <rasmus@kaj.se> wrote this file.  As long as you retain this notice you
.\" can do whatever you want with this stuff. If we meet some day, and
.\" you think this stuff is worth it, you can buy me a beer in return.
.\"
.\" $Id: imap-from.1,v 1.8 2007/12/18 12:35:52 rasmus Exp $
.\"
.\" Note: The date here should be updated whenever a non-trivial
.\" change is made to the manual page.
.Dd December 17, 2007
.Dt imap-from 1
.\" Note: .Os with no arguments, since it's not specific to any OS.
.Os
.Sh NAME
.Nm imap-from
.Nd Lists unread messages in a set of imap folders
.Sh SYNOPSIS
.Nm
.Op Fl h
.Op Fl a
.Op Fl l Ar num
.Op Fl r
.Op Fl s Ar host
.Op Fl u Ar user
.Op Fl w Ar num
.Op Fl z
.Op folders
.Sh DESCRIPTION
The 
.Nm
program checks for unread messages in an imap folder or set of folders
and prints a summary of each such message.
The summary line contains the From and Subject header lines from the messages.
.Pp
The options are as follows:
.Bl -tag -width mmsmhost -compact
.It Fl h
Display a brief help message listing the options and exit.
.It Fl a
Show address only for the senders (strip away the real names).
.It Fl l Ar num
Show only the last
.Ar num
messages of each folder.
Default is 10.
.It Fl r
Show real name only for the senders.
.It Fl s Ar host
Use
.Ar host
as the imap server 
(default is 
.Qq imap
).
.It Fl u Ar user
Username to use for authentication; defaults to the current user.
.It Fl w Ar num
Make sure output fits in a
.Ar num
characters wide terminal.
.It Fl z
Gives 
.Qq zephyr markup
(i.e. markup suitable for athena zephyrograms)
in the output.
This option is deprecated, and will be removed in a future release
unless someone tells me (se below) they still want it.
.El
.Pp
All remaining arguments are folders to check for messages in.
If there are no remaining arguments, the folder INBOX is checked.
.Sh ENVIRONMENT
All programs in the imaputil suite uses the following environment
variable:
.Bl -tag -width ".Ev MAILHOST"
.It Ev MAILHOST
Default hostname for the imap server.
May include a colon followed by a port number.
If not set,
.Qq imap
is used as a default.
.El
.\".Sh EXAMPLES
.\".Sh DIAGNOSTICS
.\".Sh COMPATIBILITY
.Sh SEE ALSO
imap-append(1),
imap-du(1),
imap-msgchk(1),
imap-qouta(1)
.Pp
http://www.stacken.kth.se/~kaj/hack/imaputil
.Pp
RFC2060, imap v4r1.
.Sh AUTHOR
.Nm
and its manual page was written by
.An Rasmus Kaj Aq kaj@kth.se .
.Sh BUGS
Please report any you might find to
.An Rasmus Kaj Aq kaj@kth.se .
